src/Entity/Bien.php
<?php

namespace App\Entity;

use App\Repository\BienRepository;
use App\Entity\TypeBien;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BienRepository::class)]
class Bien
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nomBien = null;

    #[ORM\Column(length: 255)]
    private ?string $adresseBien = null;

    #[ORM\Column(type: 'integer')]
    private ?int $prixBien = null;

    #[ORM\Column(length: 255)]
    private ?string $typeOffre = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    private ?bool $AfficherPrix = null;

    #[ORM\ManyToOne(inversedBy: 'bien')]
    private ?Gouvernorat $gouvernorat = null;

    #[ORM\ManyToOne(inversedBy: 'biens')]
    private ?Ville $ville = null;

    #[ORM\ManyToOne(inversedBy: 'biens')]
    private ?TypeBien $type = null;

    /**
     * @var Collection<int, DetailsPropriete>
     */
    #[ORM\OneToMany(targetEntity: DetailsPropriete::class, mappedBy: 'bien', cascade: ['remove'], orphanRemoval: true)]

    private Collection $detailsProprietes;

    /**
     * @var Collection<int, ImageBien>
     */
    #[ORM\OneToMany(targetEntity: ImageBien::class, mappedBy: 'bien', cascade: ['persist', 'remove'])]
    private Collection $imageBiens;

    
    #[ORM\OneToMany(targetEntity: Favoris::class, mappedBy: 'bien')]
    private Collection $favoris;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $dateCreation = null;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $publierPar = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $positionMap = null;

    #[ORM\Column(length: 255)]
    private ?string $nomProprietaire = null;

    #[ORM\Column(length: 255)]
    private ?string $telProprietaire1 = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $telProprietaire2 = null;

    #[ORM\Column(length: 255)]
    private ?string $adresseProprietaire = null;

    #[ORM\Column(type: "boolean", options: ["default" => true])]
    private bool $bienAfficher = true;


    #[ORM\OneToMany(mappedBy: 'bien', targetEntity: Transaction::class, orphanRemoval: true)]
    private ?Collection $transactions = null;

   
    
    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $youtubeId = null;

    #[ORM\Column(type: 'string', length: 20)]
    private ?string $disponibilite = 'Disponible'; // Valeur par défaut

    public const DISPONIBILITE_OPTIONS = ['Disponible', 'Louee', 'Non_disponible'];
    
    public function __construct()
    {
        $this->imageBiens = new ArrayCollection();
        $this->dateCreation = new \DateTime();
        $this->favoris = new ArrayCollection();
        $this->transactions = new ArrayCollection();
        $this->detailsProprietes = new ArrayCollection();
        
    }

    public function setCreationDate(): void
    {
        if ($this->dateCreation === null) {
            $this->dateCreation = new \DateTime();
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomBien(): ?string
    {
        return $this->nomBien;
    }

    public function setNomBien(string $nomBien): static
    {
        $this->nomBien = $nomBien;

        return $this;
    }



    public function getAdresseBien(): ?string
    {
        return $this->adresseBien;
    }

    public function setAdresseBien(string $adresseBien): static
    {
        $this->adresseBien = $adresseBien;

        return $this;
    }

    public function getPrixBien(): ?int
    {
        return $this->prixBien;
    }

    public function setPrixBien(int $prixBien): static
    {
        $this->prixBien = $prixBien;
        return $this;
    }

    public function getTypeOffre(): ?string
    {
        return $this->typeOffre;
    }

    public function setTypeOffre(string $typeOffre): static
    {
        $this->typeOffre = $typeOffre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;
        return $this;
    }


    public function isAfficherPrix(): ?bool
    {
        return $this->AfficherPrix;
    }

    public function setAfficherPrix(bool $AfficherPrix): static
    {
        $this->AfficherPrix = $AfficherPrix;

        return $this;
    }

    public function getGouvernorat(): ?Gouvernorat
    {
        return $this->gouvernorat;
    }

    public function setGouvernorat(?Gouvernorat $gouvernorat): static
    {
        $this->gouvernorat = $gouvernorat;

        return $this;
    }

    public function getVille(): ?Ville
    {
        return $this->ville;
    }

    public function setVille(?Ville $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getType(): ?TypeBien
    {
        return $this->type;
    }

    public function setType(?TypeBien $type): static
    {
        $this->type = $type;

        return $this;
    }

    /**
     * @return Collection<int, DetailsPropriete>
     */
    public function getDetailsProprietes(): Collection
    {
        return $this->detailsProprietes;
    }

    public function addDetailsPropriete(DetailsPropriete $detailsPropriete): static
    {
        if (!$this->detailsProprietes->contains($detailsPropriete)) {
            $this->detailsProprietes->add($detailsPropriete);
            $detailsPropriete->setBien($this);
        }

        return $this;
    }

    public function removeDetailsPropriete(DetailsPropriete $detailsPropriete): static
    {
        if ($this->detailsProprietes->removeElement($detailsPropriete)) {
            // set the owning side to null (unless already changed)
            if ($detailsPropriete->getBien() === $this) {
                $detailsPropriete->setBien(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ImageBien>
     */
    public function getImageBiens(): Collection
    {
        return $this->imageBiens;
    }

    public function addImageBien(ImageBien $imageBien): static
    {
        if (!$this->imageBiens->contains($imageBien)) {
            $this->imageBiens->add($imageBien);
            $imageBien->setBien($this);
        }

        return $this;
    }

    public function removeImageBien(ImageBien $imageBien): static
    {
        if ($this->imageBiens->removeElement($imageBien)) {
            // set the owning side to null (unless already changed)
            if ($imageBien->getBien() === $this) {
                $imageBien->setBien(null);
            }
        }

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->dateCreation;
    }

    public function setDateCreation(?\DateTimeInterface $dateCreation): static
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }

    public function getPublierPar(): ?User
    {
        return $this->publierPar;
    }

    public function setPublierPar(?User $user): self
    {
        $this->publierPar = $user;
        return $this;
    }

    public function getPositionMap(): ?string
    {
        return $this->positionMap;
    }

    public function setPositionMap(?string $positionMap): static
    {
        $this->positionMap = $positionMap;

        return $this;
    }


    public function getNomProprietaire(): ?string
    {
        return $this->nomProprietaire;
    }

    public function setNomProprietaire(string $nomProprietaire): static
    {
        $this->nomProprietaire = $nomProprietaire;

        return $this;
    }

    public function getTelProprietaire1(): ?string
    {
        return $this->telProprietaire1;
    }

    public function setTelProprietaire1(string $telProprietaire1): static
    {
        $this->telProprietaire1 = $telProprietaire1;

        return $this;
    }

    public function getTelProprietaire2(): ?string
    {
        return $this->telProprietaire2;
    }

    public function setTelProprietaire2(?string $telProprietaire2): static
    {
        $this->telProprietaire2 = $telProprietaire2;

        return $this;
    }

    public function getAdresseProprietaire(): ?string
    {
        return $this->adresseProprietaire;
    }

    public function setAdresseProprietaire(string $adresseProprietaire): static
    {
        $this->adresseProprietaire = $adresseProprietaire;

        return $this;
    }

    public function isBienAfficher(): bool
    {
        return $this->bienAfficher;
    }

    public function setBienAfficher(bool $bienAfficher): static
    {
        $this->bienAfficher = $bienAfficher;
        return $this;
    }

    public function getTransactions(): ?Collection
    {
        return $this->transactions;
    }

    public function setTransactions(?Collection $transactions): self
    {
        $this->transactions = $transactions;

        return $this;
    }

    public function getYoutubeId(): ?string
    {
        return $this->youtubeId;
    }

    public function setYoutubeId(?string $youtubeId): self
    {
        $this->youtubeId = $youtubeId;
        return $this;
    }

    public function getDisponibilite(): ?string
    {
        return $this->disponibilite;
    }

    public function setDisponibilite(string $disponibilite): self
    {
        if (!in_array($disponibilite, self::DISPONIBILITE_OPTIONS)) {
            throw new \InvalidArgumentException("Disponibilité invalide.");
        }
        $this->disponibilite = $disponibilite;

        return $this;
    }



}

src/Controller/Front/Accueil/AccueilController.php
<?php
namespace App\Controller\Front\Accueil;

use App\Repository\UserRepository;
use App\Repository\BienRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AccueilController extends AbstractController
{
    #[Route('', name: 'app_front_accueil_accueil')]
    public function index(UserRepository $userRepository, BienRepository $bienRepository): Response
    {
        // Fetch all users
        $admins = $userRepository->findAll();

        // Filter users with the 'ROLE_ADMIN'
        $adminsWithRole = array_filter($admins, function($user) {
            return in_array('ROLE_ADMIN', $user->getRoles());
        });

        // Récupérer tous les biens avec leurs relations
        $biens = $bienRepository->findAllWithRelations();

        // Récupérer le nombre total de biens par type
        $biensCounts = $bienRepository->countByType();

        $biens = $bienRepository->findLastFiveBiens();


        // Reformater les résultats pour un accès plus facile dans Twig
        $stats = [];
        foreach ($biensCounts as $row) {
            $stats[$row['nomType']] = $row['total'];
        }


        return $this->render('front/accueil/accueil.html.twig', [
            'admins' => $adminsWithRole,
            'biens' => $biens,
            'stats' => $stats,
        ]);
    }
}

src/Controller/Front/AllBiens/A_Louer/BienLouerController.php
<?php

namespace App\Controller\Front\AllBiens\A_Louer;

use App\Entity\Bien;
use App\Repository\BienRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BienLouerController extends AbstractController
{
    #[Route('/front/all/biens/louer', name: 'app_front_all_biens_louer')]
    public function index(
        EntityManagerInterface $entityManager, 
        PaginatorInterface $paginator, 
        BienRepository $bienRepository, 
        Request $request
    ): Response {
        // Créer une requête pour récupérer les biens visibles avec typeOffre = "A Louer"
        $qb = $entityManager->getRepository(Bien::class)->createQueryBuilder('b');

        // Appliquer les filtres
        $qb->where('b.typeOffre = :typeOffre')
        ->andWhere('b.bienAfficher = true')  // Filtrer les biens visibles
        ->setParameter('typeOffre', 'A Louer');

        // Filtre par ID (si fourni)
        if ($id = $request->query->get('id')) {
            $qb->andWhere('b.id = :id')->setParameter('id', $id);
        }

        // Filtre par Type de Bien (nomType)
        if ($nomType = $request->query->get('nomType')) {
            $qb->join('b.type', 't')  
            ->andWhere('t.nomType = :nomType')
            ->setParameter('nomType', $nomType);
        }

        // Filtre par Gouvernorat
        if ($gouvernorat = $request->query->get('gouvernorat')) {
            $qb->join('b.gouvernorat', 'g')  
            ->andWhere('g.nomGouvernorat = :nomGouvernorat')
            ->setParameter('nomGouvernorat', $gouvernorat);
        }

        // Récupérer les valeurs de prixMin et prixMax depuis la requête
        $prixMin = $request->query->get('prixMin');
        $prixMax = $request->query->get('prixMax');

        // Vérifier et appliquer les filtres
        if (!empty($prixMin)) {
            $qb->andWhere('b.prixBien >= :prixMin')
            ->setParameter('prixMin', (int) $prixMin);
        }

        if (!empty($prixMax)) {
            $qb->andWhere('b.prixBien <= :prixMax')
            ->setParameter('prixMax', (int) $prixMax);
        }




        // Tri par option
        $orderby = $request->query->get('orderby');
        switch ($orderby) {
            case 'date':
                $qb->orderBy('b.dateCreation', 'DESC');
                break;
            case 'price':
                $qb->orderBy('b.prixBien', 'ASC');
                break;
            case 'price-desc':
                $qb->orderBy('b.prixBien', 'DESC');
                break;
            default:
                $qb->orderBy('b.id', 'ASC');  // Tri par défaut
                break;
        }

        // Paginer les résultats
        $biens = $paginator->paginate(
            $qb->getQuery(),
            $request->query->getInt('page', 1), 
            3
        );

        // Compter le nombre de biens "A Louer" visibles
        $countBiensALouer = $bienRepository->countByTypeOffre('A Louer', true);

        // Retourner la vue avec les résultats
        return $this->render('front/all_biens/A_Louer/liste_prop_louer.html.twig', [
            'biens' => $biens,
            'countBiensALouer' => $countBiensALouer
        ]);
    }

}

src/Controller/Front/Chatboot/ChatbootController.php
<?php

namespace App\Controller\Front\Chatboot;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class ChatbootController extends AbstractController
{
    #[Route('/chat', name: 'chat', methods: ['POST'])]
    public function chat(Request $request): JsonResponse
    {
        // Liste des questions et réponses
        $responses = [
            "vous etes qui" => "Nous sommes l'agence immobilière **HabiLux**, créée en 2024. Nos fondateurs sont **Ahmed Ksontini** et **Bilel Maghrebi**. Notre mission est de vous aider à trouver l'appartement, la villa, le terrain ou le bureau commercial de vos rêves. 🏡✨",
            "comment je peux trouver les bien" => "Trouver nos biens disponibles est **très simple** ! 🏠\n👉 Il vous suffit de cliquer sur **Propriétés** dans le menu, et vous aurez accès à **toutes nos offres**.",
            "jai une villa, appartement, burau, terrain a vendre est ce que je peux le partager dans cette platforme" => "Bien sûr ! Nous sommes là pour répondre à vos besoins. 🏡🔑\n📩 Vous pouvez nous contacter à **Contact@habilux.com**\n📞 Ou nous appeler au **93 313 278 / 55 236 485**."
        ];

        // Récupérer le message de l'utilisateur
        $data = json_decode($request->getContent(), true);
        $userMessage = strtolower(trim($data['message'] ?? ''));

        // Vérifier la réponse correspondante
        $responseMessage = $responses[$userMessage] ?? "Désolé, je ne comprends pas votre question. ❌\nEssayez de poser une autre question ! 😊";

        return new JsonResponse(['response' => $responseMessage]);
    }
}

src/Controller/Front/Team/TeamController.php
<?php

namespace App\Controller\Front\Team;

use App\Repository\UserRepository; // Assurez-vous d'avoir le bon namespace pour votre repository User
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TeamController extends AbstractController
{
    #[Route('/front/team/team', name: 'app_front_team_team')]
    public function index(UserRepository $userRepository): Response
    {
        // Récupérer tous les utilisateurs avec le rôle ROLE_ADMIN
        $admins = $userRepository->findAll();  // Récupère tous les utilisateurs

        // Filtrer les utilisateurs avec le rôle ROLE_ADMIN
        $adminsWithRole = array_filter($admins, function($user) {
            return in_array('ROLE_ADMIN', $user->getRoles());
        });

        // Passer les données à la vue
        return $this->render('front/team/listeTeam.html.twig', [
            'admins' => $adminsWithRole,
        ]);
    }
}

templates/front/liste_favoris/liste_favoris.html.twig
{% extends 'baseFront.html.twig' %}

{% block title %}HabiLux-Propriétés{% endblock %}

{% block body %}

<style>
.property-thumb img {
    width: 475px;  /* Ajuste la largeur pour s'adapter au conteneur */
    height: 490px; /* Fixe une hauteur uniforme */
    object-fit: cover; /* Permet de conserver le rapport d'aspect et de remplir le cadre */
    border-radius: 30px; /* Optionnel : Ajoute des coins arrondis pour un meilleur rendu */
}

.user-photo {
    width: 50px; /* Taille de l'avatar */
    height: 50px; /* Taille de l'avatar */
    border-radius: 50%; /* Cette propriété rend l'image circulaire */
    object-fit: cover; /* Cette propriété ajuste l'image pour qu'elle remplisse complètement le cercle sans déformer l'image */
    border: 2px solid #fff; /* Optionnel : ajoute une bordure blanche autour de l'image */
    }

    .th-btn.style-border2.th-btn-icon i {
    color: #1C2D37; /* Couleur bleue par défaut */
    transition: color 0.3s ease-in-out; /* Animation fluide */
}

.th-btn.style-border2.th-btn-icon:hover i {
    color: white; /* Couleur blanche au survol */
}

.no-favorites {
    text-align: center;
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
}

.no-favorites-img {
    width: 100px;
    height: auto;
    margin-bottom: 15px;
}

.no-favorites p {
    font-size: 16px;
    color: #33333382;
    font-weight: bold;
}

    .alert {
        position: fixed;
        top: 20px;
        right: 20px;
        z-index: 9999;
        padding: 15px;
        color: white;
        border-radius: 5px;
        font-size: 16px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    }

    .alert.alert-success {
        background-color: #D6F4D7FF;
        color: #3E8B33FF;
        border-color: #D6F4D7FF;

    }

    .alert.alert-danger {
        color: #a94442;
        background-color: #f2dede;
        border-color: #ebccd1;
    }

    .property-card-thumb {
        position: relative;
        overflow: hidden;
        width: 100%;
        height: 250px; /* Hauteur fixe */
    }

    .property-card-thumb img {
        width: 100%;
        height: 100%;
        object-fit: cover; /* Assure un bon cadrage */
        transition: transform 0.3s ease-in-out;
    }

    .property-card-thumb:hover img {
        transform: scale(1.05); /* Zoom léger au survol */
    }

    .property-info-overlay {
        position: absolute;
        bottom: 0;
        left: 0;
        width: 100%;
        height: 55%; /* L'overlay prend 30% de la hauteur */
        background: rgba(0, 0, 0, 0.7); /* Fond semi-transparent */
        color: white;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        text-align: center;
        padding: 5px;
        opacity: 0;
        transform: translateY(100%);
        transition: opacity 0.3s ease-in-out, transform 0.3s ease-in-out;
    }

    .property-card-thumb:hover .property-info-overlay {
        opacity: 1;
        transform: translateY(0);
    }

    .property-card-title a {
        color: white; /* Texte en blanc */
        font-size: 16px;
        font-weight: bold;
        text-decoration: none;
    }

    .property-card-price {
        font-size: 14px;
        font-weight: bold;
        color: white; /* Prix en blanc */
    }

    .property-card-location {
        font-size: 12px;
        color: white; /* Localisation en blanc */
        margin-bottom: 5px;
    }

    .property-info-overlay .btn-wrap {
        margin-top: 5px;
    }

    .property-info-overlay .th-btn {
        background-color: #C0CDD1; /* Couleur du bouton */
        color: black; /* Texte du bouton en noir pour le contraste */
        padding: 6px 10px;
        border-radius: 5px;
        text-decoration: none;
        font-size: 12px;
    }

    .property-info-overlay .th-btn:hover {
        background-color: #A0B3B8; /* Assombri légèrement au survol */
    }

    .offer-tag {
    position: absolute;
    top: 10px;
    left: 10px;
    color: white;
    padding: 5px 10px;
    font-size: 14px;
    font-weight: bold;
    border-radius: 5px;
    text-transform: uppercase;
    z-index: 10;
    box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.2);
    }


    .tag-sale {
        background-color: #ff4d4d; /* Rouge pour "A Vendre" */
    }

    .tag-rent {
        background-color: #f1c643; /* Bleu pour "A Louer" */
    }

    @media (min-width: 1200px) {
        .col-xl-4 {
            width: 26.333333%;
        }
    }

</style>
    <div class="breadcumb-wrapper " data-bg-src="{{ asset('assetsFront/img/bg/breadcumb-bg.jpg') }}">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-9">
                    <div class="breadcumb-content">
                        <h1 class="breadcumb-title">Liste favoris</h1>
                        <ul class="breadcumb-menu">
                            <li><a href="{{ path('app_front_accueil_accueil') }}">Accueil</a></li>
                            <li>Favoris</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<!--==============================
Property Page Area
==============================-->
  <section class="space-top space-extra-bottom">
        <div class="container">
                        {% if app.session.flashBag.has('success') %}
                            <div id="alert" class="alert alert-success" style="display: none;" role="alert">
                                <strong>Succès!</strong> {{ app.session.flashBag.get('success')[0] }}
                                <button aria-label="Close" class="btn-close" data-bs-dismiss="alert" type="button">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        {% if app.session.flashBag.has('error') %}
                            <div id="alert" class="alert alert-danger" style="display: none;" role="alert">
                                <strong>Erreur!</strong> {{ app.session.flashBag.get('error')[0] }}
                                <button aria-label="Close" class="btn-close" data-bs-dismiss="alert" type="button">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
            
            <div class="tab-content" id="nav-tabContent">
                <div class="tab-pane fade active show" id="tab-list" role="tabpanel" aria-labelledby="tab-shop-list">
                    <div class="row gy-40">
                        {% for favori in favoris %}
                            {% set bien = favori.bien %} {# Récupérer le bien favori #}
                            <div class="col-md-6 col-xl-4">
                                <div class="property-card2">
                                    <div class="property-card-thumb">
                                        <img src="{{ asset('uploads/images_bien/' ~ bien.imageBiens|first.nomImage) }}" alt="Image du bien">
                                        <!-- Ajout du tag de type d'offre -->
                                        <span class="offer-tag {{ bien.typeOffre == 'A Vendre' ? 'tag-sale' : 'tag-rent' }}">
                                            {{ bien.typeOffre }}
                                        </span>
                                        <div class="property-info-overlay">
                                            <h4 class="property-card-title" style="font-size: 15px;">
                                                <a href="{{ path('app_front_all_biens_details_prop', {'id': bien.id}) }}">{{ bien.nomBien }}</a>
                                            </h4>

                                            <h5 class="property-card-price" style="color: white;">
                                                {% if bien.afficherPrix %}
                                                    {{ bien.prixBien|number_format(0, '', '.') }} {{ bien.typeOffre == 'A Louer' ? 'DT/Mois' : 'DT' }}
                                                {% else %}
                                                    Prix Privée
                                                {% endif %}
                                            </h5>


                                            {# Nouvelle ligne pour afficher l'adresse du bien #}
                                            <p class="property-card-address" style="color: white; font-size: 12px;">
                                                <i class="fas fa-map-marker-alt"></i> {{ bien.adresseBien }}
                                            </p>

                                            <div class="btn-wrap">
                                                <a href="{{ path('app_front_all_biens_details_prop', {'id': bien.id}) }}" class="th-btn">
                                                    <i class="fas fa-info-circle" style="color:black;"></i> Détails
                                                </a>
                                            </div>
                                        </div>

                                        <span class="delete-favori" data-id="{{ favori.id }}" style="cursor: pointer; color: red; font-size: 20px; position: absolute; top: 10px; right: 10px;">
                                            <i class="fa-solid fa-heart favorite-icon"></i>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        {% else %}
                            <div class="no-favorites">
                                <img src="{{ asset('assetsFront/img/icon/aucun-resultat.png') }}" alt="Aucun résultat" class="no-favorites-img">
                                <h4 style="color:#1C2D37;">Aucune annonce sauvegardée</h4>
                                <p>Pour consulter une annonce sauvegardée, effectuez d'abord une recherche puis cliquez sur le petit cœur pour l'ajouter à vos favoris.</p>
                            </div>
                        {% endfor %}
                    </div>

               


            </div>
            <div class="mt-60 text-center">
    {% if biens.items|length > 0 %}
        <div class="th-pagination">
            <ul>
                {% if biens.currentPageNumber > 1 %}
                    <li>
                        <a class="prev-page" href="{{ path('app_front_liste_favoris', { page: biens.currentPageNumber - 1 }) }}">
                            <i class="far fa-arrow-left me-2"></i>Précédent
                        </a>
                    </li>
                {% endif %}

                {% for page in 1..biens.pageCount %}
                    <li>
                        <a href="{{ path('app_front_liste_favoris', { page: page }) }}" class="{{ page == biens.currentPageNumber ? 'active' : '' }}">
                            {{ page }}
                        </a>
                    </li>
                {% endfor %}

                {% if biens.currentPageNumber < biens.pageCount %}
                    <li>
                        <a class="next-page" href="{{ path('app_front_liste_favoris', { page: biens.currentPageNumber + 1 }) }}">
                            Suivant<i class="far fa-arrow-right ms-2"></i>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    {% endif %}
</div>


        </div>
    
        </section>

        <!-- style notification -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script type="text/javascript">
    // Lorsque la page est prête
    $(document).ready(function() {
        // Si un message flash 'success' est présent
        if ($('#alert').length) {
            // Afficher l'alerte avec fadeIn
            $('#alert').fadeIn(500).delay(5000).fadeOut(500); // 5 secondes d'affichage
        }
    });
</script>

<script>
document.querySelectorAll('.delete-favori').forEach((element) => {
    element.addEventListener('click', function () {
        const favoriId = this.dataset.id;

        if (confirm('Voulez-vous vraiment supprimer ce favori ?')) {
            fetch(`/front/liste/favoris/delete/${favoriId}`, {
                method: 'DELETE',
                headers: {
                    'X-Requested-With': 'XMLHttpRequest'
                }
            })
                .then(response => response.json())
                .then(data => {
                    if (data.success) {
                        location.reload(); // Recharge la page
                    } else {
                        alert(data.message); // Affiche le message d'erreur renvoyé
                    }
                })
                .catch(error => console.error('Erreur:', error));
        }
    });
});
</script>

{% endblock %}